sudo: false

language: node_js

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-4.8; fi
  - export JOBS=max
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export JOBS=4; fi

os:
  - osx
  - linux

node_js:
  - 9
  - 8
  - 6
  - 4
